### ISSUE TITLE
Keyboard shortcut for running the snippet

### ISSUE THREAD

**Issue by AlexDaniel** [prasmussen/glot-www#36]
Currently you have to click “Run” which will unfocus the text editor, so if you want to edit again you will have to click on the editor. It would be more convenient if there was a shortcut, like ctrl+enter or something similar. Maybe it already exists but I couldn't find it.

**Comment by prasmussen** [comment]
Thanks for the suggestion. Ctrl+enter (and cmd+enter on mac) now works.
